name: Convert Markdown to PDF Manually

# This allows the workflow to be triggered manually
on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Convert Markdown to PDF
      run: |
        mkdir -p contents/pdf
        for file in $(find contents/md -name '*.md'); do
          filename=$(basename -- "$file")
          filename="${filename%.md}.pdf"
          pandoc "$file" -o "contents/pdf/$filename"
        done

    - name: Upload PDF files
      uses: actions/upload-artifact@v2
      with:
        name: pdf-files
        path: contents/pdf/**/*.pdf